export const types = Object.freeze({
    // Sync
    TOP_SONGS_START_FETCHING: 'TOP_SONGS_START_FETCHING',
    TOP_SONGS_STOP_FETCHING: 'TOP_SONGS_STOP_FETCHING',
    TOP_SONGS_FILL: 'TOP_SONGS_FILL',
    TOP_SONGS_SET_FETCHING_ERROR: 'TOP_SONGS_SET_FETCHING_ERROR',
    // Async
    TOP_SONGS_FETCH_ASYNC: 'TOP_SONGS_FETCH_ASYNC',
});